http:
  port: 6437
  ip: localhost
logs:
  prefix: config-follower
  console:
    active: true
    level: debug
    colorize: true
  file:
    active: false
pryv: 
  pryvApiEndpoint: "https://ck6c4o0j800wp1jd31659uur8@	
test-medisante.pryv.me"

